openapi: 3.0.0
info:
  title: skotune-ai Next.js API Route
  version: 1.0.0
paths:
  /api/auth/login:
    post:
      summary: ログイン照会BFF
      description: リクエストに合致したユーザ情報を返却
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - password
              properties:
                user_id:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: 成功時のレスポンス
        "401":
          description: 認証失敗
        "422":
          description: バリデーションエラー
  /api/search/tune:
    post:
      summary: 楽曲検索BFF
      description: リクエストに合致した歌手・楽曲情報を返却
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - artist_name
                - tune_name
              properties:
                artist_name:
                  type: string
                tune_name:
                  type: string
      responses:
        "200":
          description: 成功時のレスポンス
        "422":
          description: バリデーションエラー
        "500":
          description: 内部サーバーエラー
  /api/search/artist/tune:
    post:
      summary: 全楽曲取得BFF
      description: リクエストに合致した歌手の楽曲を全て返却
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - artist_id
              properties:
                artist_id:
                  type: string
      responses:
        "200":
          description: 成功時のレスポンス
        "422":
          description: バリデーションエラー
        "500":
          description: 内部サーバーエラー
